[package]
name = "level2"
version = "0.1.0"
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.11.2"
spl-token = { version = "*", features = ["no-entrypoint"] }
borsh = "0.9.1"
borsh-derive = "0.9.1"

[lib]
crate-type = ["cdylib", "lib"]
